[project]
name = "stowify"
version = "0.1.0"
description = "Move files into a stow-compatible structure"
readme = "README.md"
requires-python = ">=3.8"

[project.urls]
"Homepage" = "https://github.com/vha/stowify"
"Source" = "https://github.com/vha/stowify"

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"
